#config_version=4

switches:
  s_left_flipper:
    number:
    tags: left_flipper
  s_right_flipper:
    number:
    tags: right_flipper

coils:
  c_flipper_left_main:
    number:
    pulse_ms: 20
  c_flipper_left_hold:
    number:
    allow_enable: true
  c_flipper_right_main:
    number:
    pulse_ms: 20
  c_flipper_right_hold:
    number:
    allow_enable: yes

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3

keyboard:
  z:
    switch: s_left_flipper
  "/":
    switch: s_right_flipper

window:
  width: 600
  height: 200
  title: Texas Chainsaw Massacre

displays:
  window:
    width: 600
    height: 200
  dmd:
    width: 128 # This is the actual number of dots
    height: 32 # This is the actual number of dots
    default: yes

slides:
  window_slide_1:
    - type: dmd
      width: 512
      height: 128
      pixel_color: ff5500
    - type: text
      text: TEXAS CHAINSAW MASSACRE
      anchor_y: top
      y: top-3
      font_size: 30
    - type: rectangle
      width: 514
      height: 130
  test_slide:
    - type: image
      image: leatherface
      width: 128
      height: 32
      anchor_x: left
      anchor_y: bottom
      x: 0
      y: -20

slide_player:
  init_done:
    window_slide_1:
      target: window
  mode_attract_started: test_slide
